# Generated by Django 2.0.2 on 2018-03-03 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Keyword')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Frequency')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='up_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 22, 27, 3, 486129, tzinfo=utc), verbose_name='Date uploaded'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_image',
            field=models.ImageField(upload_to='artwork/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Artwork'),
        ),
    ]
