# Generated by Django 2.0.2 on 2018-03-08 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180303_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='User Name')),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='up_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 21, 21, 11, 762432, tzinfo=utc), verbose_name='Date uploaded'),
        ),
    ]
