# Generated by Django 2.0.2 on 2018-03-08 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180308_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='up_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 21, 29, 20, 502945, tzinfo=utc), verbose_name='Date uploaded'),
        ),
    ]
