# Generated by Django 2.0.2 on 2018-03-28 15:11

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180308_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='up_date',
            field=models.DateTimeField(default=game.models.getCurrentTime, verbose_name='Date uploaded'),
        ),
    ]
