# Generated by Django 2.0.2 on 2018-03-28 15:12

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180328_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='User Name')),
                ('next_art', models.ForeignKey(default=game.models.randomArt, on_delete=django.db.models.deletion.CASCADE, to='game.Artwork')),
            ],
        ),
    ]
