# Generated by Django 2.0.2 on 2018-03-28 15:19

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='next_art',
            field=models.ForeignKey(default=game.models.randomArt, on_delete=models.SET(game.models.randomArt), to='game.Artwork'),
        ),
    ]
