# Generated by Django 2.0.2 on 2018-04-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180402_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['id']},
        ),
    ]
