# Generated by Django 2.0.2 on 2018-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_playerword'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curr_timer',
            field=models.PositiveIntegerField(default=60, verbose_name='Current Time Left'),
        ),
        migrations.AddField(
            model_name='playerword',
            name='pts',
            field=models.PositiveIntegerField(default=0, verbose_name='Points'),
        ),
    ]
