# Generated by Django 2.0.2 on 2018-04-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180424_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artist Name'),
        ),
    ]
