# Generated by Django 2.0.2 on 2018-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_artwork_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Category'),
        ),
    ]
