# Generated by Django 2.0.2 on 2018-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20180426_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curr_score',
            field=models.PositiveIntegerField(default=0, verbose_name="Current Game's Score"),
        ),
    ]
