# Generated by Django 2.0.2 on 2018-04-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20180430_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
    ]
