# Generated by Django 2.0.2 on 2018-04-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_artwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Category'),
        ),
    ]
